server:
  port: 8080
logging:
  level:
    com:
      chat: DEBUG

  file:
    name: /home/kali/Desktop/msg.log
    max-history: 2
    max-size: 100KB
    total-size-cap: 400KB
  pattern:
    file: "%d [%thread] %-5level %-10logger{100} :: %msg %L %n"
    console:  "%d [%thread] %-5level %-10logger{100} :: %msg %L %n"
    rolling-file-name: "/home/kali/Desktop/%d{yyyy-MM-dd}-%i-msg.log"
